name: Playwright Tests with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Установка Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Шаг 3: Установка зависимостей
    - name: Install dependencies
      run: npm install

    # Шаг 4: Исправление прав доступа для allure
    - name: Fix permissions for Allure
      run: chmod +x ./node_modules/.bin/allure

    # Шаг 5: Установка Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Шаг 6: Запуск тестов Playwright
    - name: Run Playwright tests
      run: npx playwright test

    # Шаг 7: Генерация Allure отчета
    - name: Generate Allure Report
      run: npx allure generate allure-results --clean

    # Шаг 8: Публикация Allure отчета на GitHub Pages
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report