name: QA_GURU_BugHunter_Project_Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # Шаг 4: Устанавливаем Playwright браузеры
      - name: Install Playwright browsers
        run: npx playwright install

      # Шаг 5: Запускаем тесты Playwright
      - name: Run Playwright tests
        run: npm run test

      # Шаг 6: Сохраняем результаты Allure
      - name: Save Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      # Шаг 7: Получаем историю отчетов Allure
      - name: Get Allure History
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # Шаг 8: Генерируем Allure отчет
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      # Шаг 9: Деплоим Allure отчет на GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
