name: Playwright Tests with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Установка репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Установка зависимостей
    - name: Install dependencies
      run: npm install

    # Исправление прав доступа
    - name: Fix permissions
      run: chmod +x node_modules/.bin/playwright

    # Установка Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Запуск тестов Playwright
    - name: Run Playwright tests
      run: npx playwright test

    # Генерация Allure отчета
    - name: Generate Allure Report
      run: npx allure generate allure-results --clean

    # Публикация Allure отчета на GitHub Pages
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
