name: QA_GURU_BugHunter_Project_Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 4: Установка браузеров Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Шаг 5: Запуск тестов Playwright
      - name: Run Playwright tests
        run: npm run test

      # Шаг 6: Сохранение результатов Allure
      - name: Save Allure Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 10

      # Шаг 7: Генерация отчёта Allure (альтернатива)
      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean
          npx allure open

      # Шаг 8: Публикация отчёта Allure на GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

