name: QA_GURU_BugHunter_Project_Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 4: Установка браузеров Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Шаг 5: Запуск тестов Playwright
      - name: Run Playwright tests
        run: npm run test

      # Шаг 6: Сохранение результатов Allure
      - name: Save Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 10

      # Шаг 7: Получение истории Allure
      - name: Get Allure History
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      # Шаг 8: Генерация отчёта Allure
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10

      # Шаг 9: Публикация отчёта Allure на GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
